version: "3.9"

services:
  {{SERVICE.ANTI_VIRUS.NAME}}:
    build:
      context: .
      args:
        FACTORY_SERVICE: "true"
        UTILS_HOME: {{SYSTEM.UTILS_HOME}}
        MAIN_PORT: {{SERVICE.ANTI_VIRUS.PORTS.PORT}}
    container_name: {{SERVICE.ANTI_VIRUS.NAME}}
    hostname: {{SERVICE.ANTI_VIRUS.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{PROXY.HOME}}:{{PROXY.HOME}}
      - {{SERVER.HOME}}/Server/ClamAV/Log:/var/log
      - {{SERVER.HOME}}/Server/Dovecot/VMail:/target/vmail
      - {{SERVER.HOME}}/Server/Dovecot/Maildir:/target/maildir
      - {{SERVER.HOME}}/Server/ClamAV/Definitions:/var/lib/clamav

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
