version: "3.9"

services:
  {{SERVICE.ANTI_VIRUS.NAME}}:
    build:
      context: .
      args:
        FACTORY_SERVICE: "true"
        PROXY_HOME: {{PROXY.HOME}}
        UTILS_HOME: {{SERVER.UTILS_HOME}}
        proxy_host_ip: {{PROXY.HOST}}
        MAIN_PORT: {{SERVICE.ANTI_VIRUS.PORTS.PORT}}
    container_name: {{SERVICE.ANTI_VIRUS.NAME}}
    hostname: {{SERVICE.ANTI_VIRUS.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.UTILS_HOME}}:{{SERVER.UTILS_HOME}}
      - {{SERVER.HOME}}/Server/ClamAV/Log:/var/log
      - {{SERVER.HOME}}/Server/Dovecot/VMail:/target/vmail
      - {{SERVER.HOME}}/Server/Dovecot/Maildir:/target/maildir
      - {{SERVER.HOME}}/Server/ClamAV/Definitions:/var/lib/clamav

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
