version: "3.7"

services:
  {{SERVICE.ANTI_VIRUS.NAME}}:
    env_file:
      - ./default.env
    build:
      context: .
      args:
        # TODO: Remove
        UTILS_HOME: $UTILS_HOME
        MAIN_PORT: $MAIN_PORT
    container_name: {{SERVICE.ANTI_VIRUS.NAME}}
    hostname: {{SERVICE.ANTI_VIRUS.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/ClamAV/Log:/var/log
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/VMail:/target/vmail
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Maildir:/target/maildir
      - {{SERVER.SERVER_HOME}}/Server/ClamAV/Definitions:/var/lib/clamav

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
