version: "3.7"

services:
  {{SERVICE.MAIL_SEND.NAME}}:
    build:
      context: .
      args:
        - DB_NAME={{SERVICE.DATABASE.NAME}}
        - AV_NAME={{SERVICE.ANTI_VIRUS.NAME}}
        - DB_PORT={{SERVICE.DATABASE.PORTS.PORT}}
        - AV_PORT={{SERVICE.ANTI_VIRUS.PORTS.PORT}}
        - AV_PORT_MAIL_SEND={{SERVICE.MAIL_SEND.PORTS.PORT_ANTI_VIRUS}}
        - SERVICE_RECEIVE={{SERVICE.MAIL_RECEIVE.NAME}}
    container_name: {{SERVICE.MAIL_SEND.NAME}}
    hostname: {{SERVICE.MAIL_SEND.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - 465:465
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.CERTIFICATION.CERTIFICATES}}:/certificates
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Data:/var/lib/postfix
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Queue:/var/spool/postfix
      - {{SERVER.SERVER_HOME}}/Server/Postfix/VMail:/usr/local/vmail
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Mail:/var/spool/mail
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Log:/var/log/postfix

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
