version: "3.9"

services:
  {{SERVICE.MAIL_SEND.NAME}}:
    build:
      context: .
      args:
        FACTORY_SERVICE: "true"
        DB_NAME: {{SERVICE.DATABASE.NAME}}
        AV_NAME: {{SERVICE.ANTI_VIRUS.NAME}}
        DB_PORT: {{SERVICE.DATABASE.PORTS.PORT}}
        AV_PORT: {{SERVICE.ANTI_VIRUS.PORTS.PORT}}
        AV_PORT_MAIL_SEND: {{SERVICE.MAIL_SEND.PORTS.PORT_ANTI_VIRUS}}
        SERVICE_RECEIVE: {{SERVICE.MAIL_RECEIVE.NAME}}
    container_name: {{SERVICE.MAIL_SEND.NAME}}
    hostname: {{SERVICE.MAIL_SEND.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - 465:465
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{PROXY.HOME}}:{{PROXY.HOME}}
      - {{SYSTEM.UTILS_HOME}}:{{SYSTEM.UTILS_HOME}}
      - {{SERVER.CERTIFICATION.CERTIFICATES}}:/certificates
      - {{SERVER.HOME}}/Server/Postfix/Data:/var/lib/postfix
      - {{SERVER.HOME}}/Server/Postfix/Queue:/var/spool/postfix
      - {{SERVER.HOME}}/Server/Postfix/VMail:/usr/local/vmail
      - {{SERVER.HOME}}/Server/Postfix/Mail:/var/spool/mail
      - {{SERVER.HOME}}/Server/Postfix/Log:/var/log/postfix

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
